// Generated by https://quicktype.io

export interface WatchProviders {
  id:      number;
  results: Results;
}

export interface Results {
  AU: Au;
  BR: Au;
  CA: Au;
  GB: Au;
  IE: Au;
  IN: Au;
  MX: Au;
  NZ: Au;
  US: Au;
}

export interface Au {
  link:      string;
  rent:      Buy[];
  buy:       Buy[];
  flatrate?: Buy[];
}

export interface Buy {
  logo_path:        string;
  provider_id:      number;
  provider_name:    string;
  display_priority: number;
}
